### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ianlivingstone** [manifoldco/torus-cli#123]
We've had a lot of questions regarding windows, it'd be great if we could add proper support. The largest change will probably be handling the Daemon socket which currently uses a Unix file socket.

There is other work as well, to acclimatize the environment to a windows user. We'll also need a decent strategy for ensuring the CLI tool continues to work on Windows through CI.

**Comment by ianlivingstone** [comment]
@jbowes You've done some thinking on this topic, can you add color?

**Comment by jbowes** [comment]
![image](https://cloud.githubusercontent.com/assets/12997/20926236/a8bad870-bb91-11e6-9bc3-115e2178b284.png)

**Comment by jbowes** [comment]
It will certainly be worth supporting the windows subsystem for linux, but hopefully that will just work, and all we'll need to do is document it.

What we're interested in here is properly supporting usage of torus compiled as a windows binary, running under `cmd.exe` (and maybe powershell, too?).

TODO:
- [ ] proper session backgrounding of the daemon for windows (we use `setsid(2)` on *nix which has direct equivalent on windows
- [ ] domain socket equivalent with proper permission setup
- [ ] sanitization of directory path lookup/creation; home dir lookups
- [ ] make sure 32 bit works? my gut feeling is there's still a lot of 32 bit usage out there for windows
- [ ] windows CI setup

**Comment by jelmersnoeck** [comment]
My plan of action for this looks as follows (for now):

- [ ] Get the daemon working (start/status/stop)
- [ ] Get basic account functions working (login, logout)

This will bring up general issues that will be widespread throughout the system for Windows (paths, file permissions etc.). Once login/logout works, it means we can also communicate with the server.

Having briefly looked into this, this will most likely mean we'll have a lot of windows specific build files.

The next step will be to get all tests working on a Windows VM. This will just be running the tests, see what and why they fail and tackle them one by one. A proper Windows CI setup will help with this as well.

- [ ] Setup Windows CI
- [ ] Get all tests passing on Windows

**Comment by ianlivingstone** [comment]
> Having briefly looked into this, this will most likely mean we'll have a lot of windows specific build files.

How are we going to organize these? I'm not familiar myself with how to organize platform specific implementations in Go.

**Comment by jelmersnoeck** [comment]
@ianlivingstone as an example:

https://github.com/golang/go/blob/master/src/net/file_unix.go
https://github.com/golang/go/blob/master/src/net/file_windows.go

You can also use the term `+build !windows`, this defines everything else than windows. That's the approach I am taking now.

I am currently setting up the Windows daemon to work over TCP instead of sockets, this is just to get the flow actually working. As a general question, would TCP be an option for Unix systems as well? We do lose user/group permission control flow, but we could potentially set up an auth flow.

**Comment by ianlivingstone** [comment]
> As a general question, would TCP be an option for Unix systems as well? 

Due to the nature of our cryptography system and the host security model, we rely on the user system (and underlying permissions) so operators can draw strict lines between who has access to that systems *root* key (the machine token value or users password) and the running daemon. 

This way, the user running the process doesn't have access to the root secret but can have access to application secrets stored in Torus.

Some reading:

* https://blog.manifold.co/a-better-way-to-deploy-secrets-to-the-cloud-4420de33e00f#.fokhz7wc0
* https://www.torus.sh/docs/latest/internals/crypto
