### ISSUE TITLE
Behaviour - Double Splat Support

### ISSUE THREAD

**Issue by ianlivingstone** [manifoldco/torus-cli#131]
I started playing around with the new `**` support with ACL, I owuld have expected the following to work:

```
$ torus allow crudl /newv2onluorg/api/production/** devops
Invalid path expression.
Invalid service.
```

However,  the following does work:

```
$ torus allow crudl /newv2onluorg/api/production/**/* devops
Policy generated and attached to the devops team.

Effect:    allow
Action(s): create, read, update, delete, list
Resource:  /newv2onluorg/api/production/*/*/*/*

Necessary permissions (read, list) have also been granted.
```

However, if you leave off the trailing slash you get:

```
$ torus allow crudl /newv2onluorg/api/production/**/ devops
Policy generated and attached to the devops team.

Effect:    allow
Action(s): create, read, update, delete, list
Resource:  /newv2onluorg/api/production/*/*/*/

Necessary permissions (read, list) have also been granted.
```

Which I believe is an invalid path?

**Comment by jeffandersen** [comment]
Not ** related, just name validation related on `torus allow` (and presumable deny)

https://github.com/manifoldco/torus-cli/blob/master/cmd/allow.go#L107

The name is naively appended, since pathexp does not contain the secret name.

**Comment by ianlivingstone** [comment]
This is still broken, if I do the following:

```
Ians-MacBook-Pro-2:torus-cli ianlivingstone$ torus allow rl /newv2onluorg/api/production/** devops
Invalid secret name.
```

**Comment by jeffandersen** [comment]
So the problem with this is that PathExp does not contain the secret name. And pathexp handles the `**` expansion, so cpaths required the secret anme to be added in addition to **.. it's a little weird, but it's a major overhaul to pull secret into pathexp
