### ISSUE TITLE
Parsing secret to scientific format when stored

### ISSUE THREAD

**Issue by DLesage25** [manifoldco/torus-cli#163]
I am storing a secret which consists of a decimal number, e.g. '5346.2346578' and when I store it and retrieve it back Torus changes it to scientific notation e.g. '5346.234+e6'.

**Comment by jbowes** [comment]
We've tried to be smart about figuring out the type of a set secret, but that rarely works out well :)

https://github.com/manifoldco/torus-cli/pull/164 will just treat everything set with torus as a string, so whatever you specify will be exactly what you get out.

**Comment by jbowes** [comment]
I've released v0.21.0 today, which includes this fix.

**Comment by DLesage25** [comment]
Thanks.
