### ISSUE TITLE
Naming collision

### ISSUE THREAD

**Issue by jzelinskie** [manifoldco/torus-cli#18]
Hey,

I just noticed this project is named the same as a project that's in a relatively similar space (distributed storage, not necessarily secrets): https://github.com/coreos/torus

**Comment by kanmeiban** [comment]
coreos/torus [project status](https://github.com/coreos/torus#project-status):
> Development on Torus at CoreOS stopped as of Feb 2017. 

I think this ticket can be closed now.

**Comment by ianlivingstone** [comment]
I agree, closing it up!
