### ISSUE TITLE
Use DialTimeout for the transport settings.

### ISSUE THREAD

**Issue by jelmersnoeck** [manifoldco/torus-cli#210]
By implementing `DialTimeout` instead of `Dial` for our Socket Dial, we ensure that we don't hang forever.

Currently, if there's an issue, it could be that the dial just "hangs". By enforcing a timeout, we make sure it stops after a certain amount of time.

Seeing that it's a local Dial, I'd suggest a timeout of 1s.

**Comment by jbowes** [comment]
+1 for 1s

**Comment by jelmersnoeck** [comment]
By extension of that, we should probably set a [Client.Timeout](https://godoc.org/net/http#Client) on the [api http.Client](https://github.com/manifoldco/torus-cli/blob/17ee2b9c749054beafe6b7253778cdb4cc04e51e/api/client.go#L53) and [registry http.Client](https://github.com/manifoldco/torus-cli/blob/17ee2b9c749054beafe6b7253778cdb4cc04e51e/registry/client.go#L49) we instantiate as well.
