### ISSUE TITLE
"Not Found: identity not found; user does not belong to org" when trying to set a machine identity secret

### ISSUE THREAD

**Issue by brettneese** [manifoldco/torus-cli#211]
We're rolling out an update to our backend infrastructure with a slightly different Mongo connection string for our apps, and we need to gracefully move from one set of machines to another.

Perfect, I thought: I'll just add a new machine and namespace the new Mongo URL under that machine's identity. That way I don't need to copy my entire environment and I don't need to worry about fudging up production. But when I go to do:

``torus set /myorg/projectname/env/*/machine-name/*/mongo_url mongodb://blah``

I get:

```
Could not set credential.
Not Found: identity not found; user does not belong to org
```

Except the machine user absolutely does belong to the organization and shows up properly under ``torus machines list --org myorg``. 

The machine name is hyphenated, if that matters. 

Is this a bug? Am I doing something wrong? This is blocking a pretty important rollout that we are trying to get done by EOW so guidance ASAP is appreciated.

FWIW: 

```
➜  ~ torus -v
CLI         0.22.0
Daemon      0.22.0
Registry    0.20.0
```

**Comment by ianlivingstone** [comment]
Could you provide me with the org name and any other relevant information via `support@torus.sh`?

**Comment by ianlivingstone** [comment]
Also, machine identities are special, they must be prefixed with `machine-${name}` where `${name}` is the name of the machine (e.g. if I have a machine named `jack`, then the identity field would be `machine-jack`).

**Comment by brettneese** [comment]
Ah, that must've been it. The docs weren't clear on that.

Closing. ;-)

**Comment by ianlivingstone** [comment]
No problem!
