### ISSUE TITLE
Windows: investigate setting up correct Security Attributes.

### ISSUE THREAD

**Issue by jelmersnoeck** [manifoldco/torus-cli#215]
As mentioned in https://github.com/manifoldco/torus-cli/pull/207/commits/5b232d73319a83bb0355add2186909fb3cc81f93, we're using the default security group settings when creating a Named Pipe.

This means that we grant read access to members of the Everyone Group and the Anonymous user.

We should have a look at what exactly the impact of this is and if we can restrict that more by setting up a correct Security Attribute when creating the Named Pipe (this would require some changes to the npipe package).

**Comment by ianlivingstone** [comment]
Closed by #333
