### ISSUE TITLE
Support `-f` on torus set

### ISSUE THREAD

**Issue by ianlivingstone** [manifoldco/torus-cli#218]
Many times, secrets are stored in a file, it'd be nice if you could import secrets from a file into torus using the set command.

Something like:

```
$ torus set -e myprod -f secrets.yml
```

Where the supported files are yaml, json, or env

**Comment by jbowes** [comment]
This makes more sense as `torus import` to me.

**Comment by ianlivingstone** [comment]
For the short term, we just discussed having this be done by reading from stdin for `key=value\n`. Allowing you to pipe a `env` file (e.g.`torus set -e prod < mysecrets`)
