### ISSUE TITLE
Not possible to override broader secrets using an instance 

### ISSUE THREAD

**Issue by brettneese** [manifoldco/torus-cli#225]
We'd like to version a secret that's already been set at:

`/org/project/environment/service/*/*/secret`

using an instance, like so: 

`/org/project/environment/service/*/beta/secret`

so that if Torus is run with a TORUS_INSTANCE=beta, the new secret is applied and if it's not, it uses the old secret.  

Unfortunately when I run:

`torus set --org org --project project --environment environment --service service --instance beta SECRET value`, I get: 

`Bad Request: secret exists for that pathexp and version`

Am I doing something wrong? Is there a better way to accomplish this task? 

I can use environments because only this variable is changing and everything else set in this environment is the same. Would be really obnoxious to copy it over.

**Comment by jeffandersen** [comment]
@brettneese I don't think the instance in this case would be the best way to approach the problem you outlined. Currently `instance` was implemented with process instances in mind, and defaults to `1`.

If you're just looking to switch between an established set of values, and a new set that you expect to transition to I'd recommend using wildcards with environments.

You could set your normal values via `/org/project/environment-*/service/*/*/secret`, and then by setting a more specific environment for your beta environment you would override `secret` e.g `/org/project/environment-beta/service/*/*/secret`.

The beta env would inherit everything set with the wildcard, but maintain the values set with the exact name `environment-beta`.

We use this a lot with development environments. We set project-wide values using `dev-*` as the environment, then each user has their own specific namespace under `dev-$username` (i.e. dev-jeff). 

Does that make sense?

@ianlivingstone may have further suggestions.

**Comment by brettneese** [comment]
@jeffandersen the downside with that approach is that I can't set something to apply for something in say, a `production` environment and a `development` environment at once... but maybe that's ok.

**Comment by jeffandersen** [comment]
@brettneese like the environment, the `service` segment also supports wildcards.

You could have beta services rather than environments, which would compartmentalize it a bit further.

**Comment by brettneese** [comment]
oooooooh that makes sense duh

closing. thanks so much for your guidance!

**Comment by jeffandersen** [comment]
No problem :)

**Comment by brettneese** [comment]
One last thing - we already have a bunch of secrets set explicitly at our service name. 

Do I need to reset them with the -* wildcard or will just appending -beta to the new secret @ org/project/environment-beta/service/*/*/secret work  (and have the beta grab all the other secrets already set.)

**Comment by jeffandersen** [comment]
Unfortunately you would have to re-set them in that namespace.

We should probably think of implementing some sort of "move" or "copy" interface. Maybe as part of the import/export commands (just have them work similarly).

**Comment by jeffandersen** [comment]
I've opened https://github.com/manifoldco/torus-cli/issues/226
