### ISSUE TITLE
Windows Install File

### ISSUE THREAD

**Issue by briangruber** [manifoldco/torus-cli#229]
Looks like windows support landed in master, but the instructions say to go to https://get.torus.sh/ to get the windows installer which doesn't seem to be there. Any idea when it will be added?

**Comment by ianlivingstone** [comment]
We just started tracking a release candidate in #230

**Comment by briangruber** [comment]
Great thanks!

**Comment by ianlivingstone** [comment]
The windows preview is now available on `get.torus.sh` :)
