### ISSUE TITLE
Getting "API Token is required" when doing "Torus run" locally 

### ISSUE THREAD

**Issue by DLesage25** [manifoldco/torus-cli#249]

**Comment by jeffandersen** [comment]
@DLesage25 Hi Daniel, could you share some more runtime details such as whether you're currently logged in or if you're using a machine token to authenticate?

What happens when you run `torus status`?

**Comment by jeffandersen** [comment]
Looks like you've come across the problem in https://github.com/manifoldco/torus-cli/issues/250

**Comment by DLesage25** [comment]
Hi @jeffandersen 
Regarding #250, these are not at all related issues, they are happening with different services and different accounts.

I am currently logged in when running Torus.
When I run torus status I see:
Org:         <my org>
Project:     <my-proj>
Environment: <my dev env>
Service:     default
Identity:    <my account>
Instance:    1

**Comment by jeffandersen** [comment]
Could you also share the version information and platform?

**Comment by DLesage25** [comment]
node v7.9.0

Torus:
CLI         0.24.0
Daemon      0.24.0
Registry    0.20.0

**Comment by ianlivingstone** [comment]
@DLesage25 have you tried logging out of Torus and logging back in? 

It's possible your session has expired.

**Comment by DLesage25** [comment]
@ianlivingstone fixd. This is actually because I was requiring "torus" and not "torus-cli". I added a PR to your Readme to note this
