### ISSUE TITLE
Secret with trailing "&" not saving properly

### ISSUE THREAD

**Issue by DLesage25** [manifoldco/torus-cli#250]
I have a password ending with a trailing & which causes torus to not save it correctly (it gets saved without the ampersand)

**Comment by ianlivingstone** [comment]
Are you quoting the value ? (E.g. Torus set x "u&")

Bash may be interpreting the &

**Comment by DLesage25** [comment]
I'm not. Should I quote strings from now on when setting them as secrets?

**Comment by ianlivingstone** [comment]
Yes, if characters are present that would need to be bash escaped.
