### ISSUE TITLE
Feature Discussion - Inject org, project, env into the environment as env variables

### ISSUE THREAD

**Issue by PLaRoche** [manifoldco/torus-cli#258]
Could be usefull to put the org, project and env being used as environment variables.

Not sure if this should be done by default or by an optional flag / config.  Also not sure if this should be shown in torus view -v

Example:
`torus run -o myorg -p myproj -e myenv -- echo $MYORG`
would result in `myorg` being echo'd out

Perhaps a standard prefix could be attached as not to stomp on other envs:
`TORUS_MYORG` as example.

**Comment by johnstonmatt** [comment]
Maybe even TORUS_CREDENTIALS and save the whole path, limiting affected namespace
