### ISSUE TITLE
Selecting multiple envs is not possible

### ISSUE THREAD

**Issue by radmen** [manifoldco/torus-cli#271]
Documentation states that:

> --environment ENV, -e ENV    Executing the command for the specified environment. Can be specified multiple times.

However it's not possible. When I try to provide `-e` flag mutliple times I'll receive values from the last provided env.

```
$ torus set -o radmen -p github FOO bar
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Completed Operation

Credential foo has been set at /radmen/github/dev-radmen/default/*/*/foo

$ torus set -o radmen -p github -e test BAR baz
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Completed Operation

Credential bar has been set at /radmen/github/test/default/*/*/bar

$ torus view -o radmen -p github -e test -e dev-radmen
FOO=bar
```

Expected:

```
FOO=bar
BAR=baz
```

```
$ torus -v
CLI         0.24.1
Daemon      0.24.1
Registry    0.20.0
```

**Comment by luizbranco** [comment]
@radmen the `env` flag usage documentation for `view` is different than `set`. Set allows multiple env, users, machines and instances. View only allows one of each.

I think it comes downs to ambiguity. On set the values are overwritten if they already exist, on view multiple envs could have different values for the same key.

For example:

```
torus set -o radmen -p github -e test port 3000
torus set -o radmen -p github -e production port 80
```

What would be the result of `torus view -o radmen -p github -e test -e production` ?

```
PORT=3000
PORT=80
```

It'd show duplicated/conflicting values, unless there are clearly separated outputs for each env or the full path for each secret.

**Comment by radmen** [comment]
> the env flag usage documentation for view is different than set. Set allows multiple env, users, machines and instances. View only allows one of each.

Well, the docs are not clear about it. They state that command options are the same for `secrets` so that was the reason why I thought that it may be a bug in client.

> It'd show duplicated/conflicting values, unless there are clearly separated outputs for each env or the full path for each secret.

I understand this problem. In such situation I'd probably expect that `PORT` value would be the one from the last specified env.

Regarding the issue - looks like the problem is more with the documentation (which is a bit vague in this context) not the cli.

**Comment by ianlivingstone** [comment]
I updated the documentation, so it should be clearer now!
