### ISSUE TITLE
DNS Dead for torus.sh??

### ISSUE THREAD

**Issue by briangruber** [manifoldco/torus-cli#272]
Is there something wrong with torus.sh? Our scripts won't connect, can't get to the website, and multiple ns lookups fail.

![image](https://user-images.githubusercontent.com/11540189/30789527-bacaf66a-a16b-11e7-8033-281bd0b52053.png)

**Comment by ianlivingstone** [comment]
We're currently experiencing issues with our `torus.sh` domain, we're extremely sorry for any outages or inconvenience this may have caused our users. This outage effects our `torus.sh` domain which hosts our website and binaries/apm/yum repositories, however, it does not effect our api services.

As a result of this outage, the torus daemon will crash while trying to check for the latest version information (which is hosted on `get.torus.sh`). To work around this issue, you can disable update checking or upgrade to the latest version (`v0.24.2`).

To disable update checking, run `torus prefs set core.check_updates false` or update `~/.torusrc` file to set `check_updates` to `false`. This will need to be run on all hosts as it's a local machine specific configuration variable.

**Example**

```bash
$ torus prefs set core.check_updates false
Preferences updated.
$ torus prefs list

/Users/test/.torusrc

[core]
    registry_uri       = https://registry.arigato.sh
    gatekeeper_address = 0.0.0.0:8200
    context            = true
    progress           = true
    hints              = true
    check_updates      = false
```

To upgrade to the latest version (`v0.24.2`), you can retrieve the binaries from the [github release page](https://github.com/manifoldco/torus-cli/releases/tag/v0.24.2) or via [npm](https://npm.im/torus-cli) (as all other distribution sources currently rely on `get.torus.sh`).

Once again, we're incredibly sorry for this outage, maintaining a reliable and performant experience for our users is top of mind. We will keep updating this issue as we work to resolve the problem.

**Comment by ianlivingstone** [comment]
For apt and yum, you will need to update the repository configuration.

- RPM based distributions: Use the following repository configuration:
```
$ sudo tee /etc/yum.repos.d/torus.repo <<-'EOF'
[torus]
name=torus-cli repository
baseurl=https://s3.amazonaws.com/get.torus.sh/rpm/$basearch/
enabled=1
gpgcheck=0
EOF
```
- DEB based distributions: Use the following repository configuration:
```
DISTRO=$(lsb_release -i | awk '{print tolower($3)}')
CODENAME=$(lsb_release -c | awk '{print $2}')
sudo tee /etc/apt/sources.list.d/torus.list <<< "deb https://s3.amazonaws.com/get.torus.sh/$DISTRO/ $CODENAME main"
```

**Comment by jeffandersen** [comment]
The website and docs are temporarily available on https://www.arigato.sh

**Comment by PLaRoche** [comment]
Update: While we wait for our upstream providers to sort out the status of our DNS records, you can update to a latest version of the CLI which works around this problem.  We apologize for this inconvenience and will keep this issue posted.

**Comment by jeffandersen** [comment]
DNS for Torus.sh is now operational.
Users who have implemented the workaround can re-enable update checking by running:

```
torus prefs set core.check_updates true
```
