### ISSUE TITLE
Repo is not signed

### ISSUE THREAD

**Issue by dyaa** [manifoldco/torus-cli#288]
I keep getting 
```sh
W: The repository 'https://get.torus.sh/ubuntu xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
```
when i do `apt-get update`

How can i solve this !?

**Comment by ianlivingstone** [comment]
Currently, our releases are not signed (we have opened #73 to track this issue as it's on our roadmap). Until we implement signing, you should be able to use the `--allow-unauthenticated` flag to skip signature verification.

**Comment by ianlivingstone** [comment]
Closing this as a duplicate, updating #73 with the workaround for now.
