### ISSUE TITLE
Import .env file function broken

### ISSUE THREAD

**Issue by PatDuJour** [manifoldco/torus-cli#296]
Importing .env file sets the wrong key-value pair.

content of .env:
```
A=C
B=D
```

Console Output
```
$ torus import .env
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Credential encrypted
Completed Operation

Credential c has been set at /{removed-pwd}/default/*/*/c
Credential d has been set at /{removed-pwd}/default/*/*/d
```
Here it shouldn't be setting values for `C` and `D`, it should be settings values for `A`and `B`.

And the output for 
```
$ torus view
C=D
D=D
```

**Comment by ianlivingstone** [comment]
I've just reproduce this issue, should have a fix out this afternoon!
