### ISSUE TITLE
Bad Request: public key has been revoked

### ISSUE THREAD

**Issue by DLesage25** [manifoldco/torus-cli#329]
When trying to change a credential, all the members of my organization are getting this log:
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Could not set credential.
Bad Request: public key has been revoked

**Comment by ianlivingstone** [comment]
I think I've found the bug, I'll put together a release as soon as I have a fix.

**Comment by ianlivingstone** [comment]
@DLesage25 I reached out via email with additional questions to the address you signed up with on Torus. Any additional information you could provide would be super helpful :)

**Comment by ianlivingstone** [comment]
This bug should now be resolved with the latest release of the torus server. You shouldn't need to upgrade, it should just work.

Please don't hesitate to re-open this issue if you run into any other issues.
