### ISSUE TITLE
Unable to remove team member

### ISSUE THREAD

**Issue by radmen** [manifoldco/torus-cli#366]
I'm trying to remove team member. Sadly, command fails.

```
$ torus teams members member

   Name                  Username
   John Doe      john
$ torus teams remove john member
Cannot remove members from the member team
```

Excerpt from `torus debug`:

```
$ DEBUG=1 torus debug
Timestamp            Thu Mar  1 12:49:30 UTC 2018
Debug                false
Session Type         user
User ID              040qpv1ebmqfkk6663ggrvd5r609y
Identity             radmen

CLI                  0.29.0
Daemon               0.29.0
Registry             0.24.1
Registry URI         https://registry.arigato.sh
```

Is there something that I'm doing wrong, or is this an error somewhere in the API?

**Comment by ianlivingstone** [comment]
All members of an organization belong to the member team, so they can't be removed. However, to remove a user from an organization you can use `torus orgs remove $username` which will remove them from the org and all associated teams.

**Comment by radmen** [comment]
Thank you! I've missed that one.
