### ISSUE TITLE
Distributing binaries on release

### ISSUE THREAD

**Issue by jhaynie** [manifoldco/torus-cli#372]
Looks like after v0.29.0 you stopped building and attaching binaries to the Github release. Are you not going to make pre-built binaries available anymore?

**Comment by ianlivingstone** [comment]
Looks like this is a bug, I'll make that these are available right away.

**Comment by ianlivingstone** [comment]
I've attached the binaries to the GitHub release, they're also available on [get.torus.sh](https://get.torus.sh).
