### ISSUE TITLE
Decrypting Credentials

### ISSUE THREAD

**Issue by ItsLeeOwen** [manifoldco/torus-cli#377]
Every nth (5th ish) time that torus run is executed, it hangs on Decrypting Credentials indefinitely until the machine is restarted, or background torus processes are force quit.

Are there any verbosity flags to help troubleshoot this?

**Comment by ianlivingstone** [comment]
Yeah, if you watch the daemon log `$HOME/.torus/daemon.log`, you should be able to see the outgoing HTTP requests from the daemon.

I'm going to dig in real quick and see if there is an obvious issue or not.

**Comment by briangruber** [comment]
Has this been resolved? Myself and several in the office seem to get this a lot and have to `torus daemon stop` or restart computer to get it off Decrypting Credentials. We are using v0.30.1

**Comment by ItsLeeOwen** [comment]
I regularly experience the originally described issue when running multiple apps simultaneously with torus-cli 0.30.1 on OSX installed via homebrew.  Stopping the running process to relogin and resume is my current workaround.
