### ISSUE TITLE
invites cannot send or accept

### ISSUE THREAD

**Issue by connorbrathwaite** [manifoldco/torus-cli#385]
`torus invites send connor@biospective.com` returns "Could not send invitation to org, please try again."

afterwards i did recieve invites @ that inbox however the verify command was also unsuccessful.

`cat .torus.json` > `{"org":"biospective","project":"g2-next"}`

**Comment by dewhacker** [comment]
We're seeing that the emails send, the sender cannot view their sends using `torus invites view`, yet the email **does** get sent.  The invitee can also cannot accept or view the invite

**Comment by eduardoromero** [comment]
Seeing the same behavior. Errors when trying to send an invite or accept one: `Could not send invitation to org, please try again.` and `Could not accept invitation to org, please try again.`

As @dewhacker mentions, the email gets out despite the error but the invite cannot be accepted, and are not shown in `torus invites list`.

**Comment by PLaRoche** [comment]
Hi all, we just pushed out an update, sorry for the delay.  This error should now be dealt with, please let us know otherwise.
