### ISSUE TITLE
template command - exporting to a file

### ISSUE THREAD

**Issue by ianlivingstone** [manifoldco/torus-cli#51]
## Problem

Configuration files are still core to many deployment flows and many developers prefer them.

Our challenge is to offer an experience that enables you to store secrets with torus while integrating seamlessly into your pre-existing deployment pipeline.

To do that, we can offer people the ability to derive configuration files at deployment time accepting the fact that these files must be kept "safe" (as they move outside the confines of the Torus ecosystem).

## Proposal

We're proposing a `torus template` command that operates exactly like `torus run` and `torus view` allow users to specify the service, environment, etc., through flags but also require a template file (e.g. `torus template -e production -s api config.json.template`).

Torus would then use the given template to generate a config file and print it to stdout. Optionally, if `--file` is provided then we will write the output to the given file path. 

For simplicity and approachability, I think the best option for a templating engine would be something like [handlebars](http://handlebarsjs.com/) which has a [decent go library](https://github.com/aymerick/raymond).

If an expected variable is not present, the template command will fail.

#### Command Help

```
NAME:
   torus template - Generate a configuration file using secrets for the given project, service, and environment. By default, the result is written to stdout.

USAGE:
   torus template [template-file] [output file] [command options]

CATEGORY:
   SECRETS

OPTIONS:
   --org ORG, -o ORG                 Use this organization.
   --project PROJECT, -p PROJECT     Use this project.
   --environment ENV, -e ENV         Use this environment.
   --service SERVICE, -s SERVICE     Use this service. (default: default)
   --user USER, -u USER              Use this user.
   --machine MACHINE, -m MACHINE     Use this machine.
   --instance INSTANCE, -i INSTANCE  Use this instance. (default: 1)
```

#### Example Usage

```
$ cat service.json.template
{
  "port": {{ port }},
  "sendgrid_token": {{ sendgrid_token }}
}

$ torus template -e production -s api service.json.template
{
  "port": 3211,
  "sendgrid_token": "wwerwerwerwrwrwre"
}

$ torus template -e production -s auth service.json.template auth.json

# For complex config files, we can offer an iterable (config) for looping over the available configuration.
$ cat complex.env.template
{
  "port": {{ config.port }},
  "sendgrid_token": "{{ config.sendgrid_token }}"
}
```

## Todo

- [x] Implement new `--format` flag with `torus view`
- [ ] Implement `torus template` command as spec'd above

**Comment by ianlivingstone** [comment]
@jeffandersen @jbowes @mattcreager feedback on the above would be great!

**Comment by rezen** [comment]
That interaction is exactly what I'm looking for!

**Comment by jbowes** [comment]
The `--format` option makes me think this should be added to `view` rather than be its own command, as the `env` format is the default output of `view`. At the least I'd move the standard format outputs to `view` and reserve `template` for custom formats only.

`view`'s `--verbose` is then just another `--format` type, and the `--verbose` flag can be deprecated.

**Comment by jbowes** [comment]
IMO the output file should be a positional argument, just like the template file. Both should accept `-` as values to indicate stdin/stdout. output file would follow the template file in ordering, and be optional.

**Comment by jeffandersen** [comment]
> The --format option makes me think this should be added to view rather than be its own 

I think we could get `--format` out there really quick this way. Especially by default for .env files, then a flat JSON structure could be substituted.

**Comment by ianlivingstone** [comment]
> The --format option makes me think this should be added to view rather than be its own command, as the env format is the default output of view. At the least I'd move the standard format outputs to view and reserve template for custom formats only.


Yeah, I think that makes sense for view -- but I think having the "templating" live under `view` would be non-intuitive.

**Comment by ianlivingstone** [comment]
I forgot to close this up, but we decided a better approach would be to begin building out native language SDKs and plugins for various tools such as ansible, etc.
