### ISSUE TITLE
Don't use revoked keys for keyring shares

### ISSUE THREAD

**Issue by jbowes** [manifoldco/torus-cli#82]
We should never use keys that are revoked when adding to a keyring:
- find the non-revoked version of a keypair for a user when adding them to a keyring, and use that
- teach the worklog to re-encode keyring membership with a non-revoked version, when a revoked one is found. This should be auto-resolvable.

This will be hard to test without having revoked keys, so:
- add `torus keypairs generate --force`to force a revocation/recreation of a set of keypairs.

**Comment by ianlivingstone** [comment]
We also need to ensure we select the right key for encryption: https://github.com/manifoldco/torus-cli/blob/master/daemon/logic/utils.go#L378

We probably want to introduce a `Claimtree` (all keys in org) and `Keypair` (users keys) struct that we can attach some methods too for finding a targeted key (and returning an error if the key is revoked or doesn't exist), selecting a valid key from the tree for use for a targeted user, etc.

Then we could introduce another method that takes the Claimtree for the arigato org and the target org to navigate down the entire tree to validate the full authenticity of the key signature chain.
