### ISSUE TITLE
Standardize invited user display

### ISSUE THREAD

**Issue by jbowes** [manifoldco/torus-cli#94]
We need to standardize how we display the subject of an invite through the invite process.

Since an invite begins as having only an email address, it makes sense to focus on that:
- pending: `person@domain.com`
- accepted: `username <person@domain.com>`
- approved: `username <person@domain.com>`

These should be updated for the `invites` commands, and for `worklog`.

**Comment by ianlivingstone** [comment]
Closed by #349
